# 公共配置文件
server:
  port: 8123
  servlet:
    context-path: /api
  application:
    name: yinterface
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
spring:
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://43.139.105.165:3308/yuapi
    driver-class-name: com.mysql.cj.jdbc.Driver
knife4j:
  enable: true
  openapi:
    title: api平台接口文档
    description: "api平台接口文档"
    email: 2480549096@qq.com
    concat: 岳海涛
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.yue.yinterface.controller
