# ??????
spring:
  application:
    name: yuapi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.105.165:3308/yuapi
    username: root
    password: 123
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session ????????
  session:
    timeout: 86400
    store-type: redis
  # redis ??
  redis:
    host: 43.139.105.165
    port: 6378
    password: 123456
    database: 1
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://43.139.105.165:8848
server:
  port: 7528
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)